---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 3-demo-source-git-bb-app
  namespace: 3-demo
spec:
  interval: 11s
  ref:
    branch: 3-demo
  url: https://github.com/Sajjadhz/bb-app-source.git
